pughlab/ctims

apps/web/pages/trials/index.tsx

The table header Status has been changed to CTML Status

CTM-184 Change Status Table Header

---

apps/web/components/Login.tsx

This PR will handle two situations
1. If the user clears a login field, the field will be highlighted in red and have warning text
2. If the user trying to login with invalid credentials, a toast will pop up warning them

CTM-167 Handle invalid logins

---

apps/api/src/app/ctml-json/ctml-json.controller.ts
apps/api/src/app/ctml-json/ctml-json.service.ts
apps/web/components/editor/EditorTopBar.tsx
apps/web/components/editor/SendCTMLtoMatchminerDialog.module.scss
apps/web/components/editor/SendCTMLtoMatchminerDialog.tsx
apps/web/hooks/useSendCTML.tsx

mm-api branch mickey_custom_ctims_endpoint

CTM-239 send ctml to matchminer

---

apps/web/components/Login.tsx
apps/web/data/strings.json

Adds
- Password reset dialog
- Updated login instructions
- Config-based strings

CTM-254 and CTM-253 Add function to password reset

---

keycloak/keycloak-compose.yml
keycloak/run-keycloak.sh

@jagnathan I added a keycloak docker compose file to make it easier to setup keycloak locally.

added keycloak docker compose

---

libs/ui/src/lib/components/forms/GenomicForm.tsx

Fixed the bug which is due to unchecked object.

CTM-401: Fixed the undefined error which crashes the front end.

---

apps/api/.env.example
apps/api/src/app/app.module.ts
apps/api/src/app/info/info.controller.ts
apps/api/src/app/info/info.module.ts
apps/api/src/app/info/info.service.ts
apps/web/components/Footer.module.scss
apps/web/components/FooterComponent.tsx
apps/web/components/Login.module.scss
apps/web/components/Login.tsx
apps/web/hooks/useGetApiInfo.tsx
apps/web/pages/main/index.module.scss
apps/web/pages/main/index.tsx
apps/web/pages/trials/create/[trialGroupId].tsx
apps/web/pages/trials/create/index.tsx
apps/web/pages/trials/edit/[id].tsx
apps/web/pages/trials/import/index.tsx

…fo on login, main and ctml pages.

Kevin ctm 374 added both backend and frontend code for api info.

---

libs/ui/src/lib/components/CtimsAutoCompleteComponent.tsx

Fixed bugs in issue #63 hugo gene symbol auto complete

Fixed bugs in issue #63 hugo gene symbol auto complete

---

libs/ui/src/lib/components/CtimsAutoCompleteComponent.tsx
libs/ui/src/lib/components/forms/GenomicForm.tsx

Revert PR "Fixed bugs in issue 63 hugo gene symbol auto complete field"

---

apps/web/pages/trials/import/index.tsx
apps/web/store/slices/contextSlice.tsx

Fixed bug where trials disappeared upon importing subsequent trials. Implemented solution to maintain visibility of all imported trials in the Trial summary page

Import bug fix CTM 373

---

apps/web/components/trials/TrialGroupsDropdown.tsx
apps/web/components/trials/Trials.module.scss

Implemented automatic selection of the trial group if the user belongs to only one trial group, and added a help message.

Dheeraj CTM 495 

---

libs/ui/src/lib/components/CtimsAutoCompleteComponent.tsx

Fixed the issue in Autocomplete component where the dropdown list is static, made necessary changes which make sure the list stays intact with the autocomplete component

Dheeraj_CTM_548

---

libs/ui/src/lib/custom-rjsf-templates/CtimsCalendar.tsx
libs/ui/src/lib/custom-rjsf-templates/CtimsCheckbox.tsx
libs/ui/src/lib/custom-rjsf-templates/CtimsDropdown.tsx
libs/ui/src/lib/custom-rjsf-templates/CtimsInput.tsx
libs/ui/src/lib/custom-rjsf-templates/CtimsInputWithExcludeToggle.tsx
libs/ui/src/lib/custom-rjsf-templates/CtimsNumberInput.tsx
libs/ui/src/lib/custom-rjsf-templates/CtimsSelectButton.tsx

Removed optional labels from all the metadata fields.

Dheeraj_CTM-549

---

apps/web/pages/trials/edit/[id].tsx
apps/web/pages/trials/import/index.tsx
libs/ui/src/lib/components/helpers.ts
libs/ui/src/lib/ui.tsx

Changed the schema of prior_treatment_requirements field while exporting a trial

Dheeraj_CTM-482

---

libs/ui/src/lib/components/CtimsFormComponent.tsx

Removed trial_internal_id field from ctims UI

Removed trial_internal_id field from ctims UI

---

libs/ui/src/lib/ui.tsx

Fixed a bug which is causing the prior requirement data to be in object format while creating  a new trial.

Dheeraj_Latest_CTM-482

---

libs/ui/src/lib/components/helpers.ts

Resolved an issue that was preventing trials from being exported when no matching criteria were specified

Dheeraj_CTM-595

---

apps/api/prisma/schema.prisma
apps/api/src/app/ctml-json/ctml-json.service.ts
apps/api/src/app/trial/trialWithResults/trial-result.service.ts
apps/api/src/app/trial/trialWithResults/trialWithResults.ts
apps/web/components/trials/Results.tsx
apps/web/hooks/useGetMatchResults.tsx

Added a new column in the results table in the ctims editor UI to view the date and time at which a trial is sent to matchminer.

Dheeraj_CTM-592

---

libs/ui/src/lib/components/forms/ClinicalForm.tsx

Changed the her2, Er and Pr status field values from True/False to Positive/Negative in UI

Dheeraj_CTM-514

---

apps/web/components/trials/Results.tsx

Added two new columns in the results csv file.

Dheeraj CTM 625

---

apps/web/components/editor/EditorTopBar.tsx
apps/web/components/trials/Results.tsx
apps/web/hooks/useSendCTML.tsx

Adding NickName and Short Title fields in output CSV file

Dheeraj_CTM-641

---

libs/ui/src/lib/components/forms/ClinicalForm.tsx

Add age and TMB tooltips; Add example to age tooltip

Add age and TMB tooltips

---

apps/web/components/trials/Results.tsx
apps/web/components/trials/Trials.tsx

- Added sort to each column in Trial/Results table

CTM-645: sort the columns in the Trials and Results page

---

apps/web/components/trials/Results.tsx
apps/web/components/trials/Trials.tsx

- Added pagination to Trial/Results table

CTM-643: pagination for the trials table

---

apps/web/components/trials/Results.module.scss
apps/web/components/trials/Results.tsx
apps/web/components/trials/Trials.module.scss
apps/web/pages/styles.css

Fixed: Shifting columns issue and weird sorting problem

Daniel ctm 645: sort the columns in the Trials and Results page

---

apps/web/components/trials/Results.tsx
apps/web/components/trials/Trials.tsx

Sorted the Trial and Result tables by the Modified on column

CTM-691: Sort the Trial and Result tables by the Modified on column

---

libs/ui/src/lib/custom-rjsf-templates/CtimsInputWithExcludeToggle.tsx

Dheeraj_CTM_656_InputToggle

---

libs/ui/src/lib/components/forms/GenomicForm.tsx
libs/ui/src/lib/components/helpers.ts

Added toggle functionality to Protein Change input text field

Dheeraj CTM 698

---

docker-compose.yml

Added all new containers and updated port numbers to docker compose file

Added all new containers and updated port numbers to docker compose file

---

libs/ui/src/lib/components/CtimsAutoCompleteComponent.module.css
libs/ui/src/lib/components/CtimsAutoCompleteComponent.tsx
libs/ui/src/lib/components/forms/GenomicForm.tsx
libs/ui/src/lib/components/helpers.ts

Adding a toggle to autocomplete component, which leads to adding a toggle in the Hugo Symbol Field

Dheeraj CTM 700

---

apps/web/components/trials/Results.tsx
apps/web/components/trials/Trials.tsx
apps/web/hooks/useGetTrialsForUsersInGroup.tsx

- Correctly formatted sort for Modified column (default sort) in Trials and Results table

Daniel ctm 691

---

libs/ui/src/lib/components/CtimsAutoCompleteComponent.tsx
libs/ui/src/lib/components/forms/GenomicForm.tsx

Added toggle functionality for Fusion Partner Hugo Symbol Field.

Dheeraj_CTM-701
